const express = require('express');
const { randomUUID } = require('crypto');
module.exports = function createChatRoutes({ requireAuth, readSettings, readJson, writeJson, path, CONVERSATIONS_DIR, CONSTITUTION, readMemory, MEMORY_PATH, TIMEZONE, callDeepSeek, writeMemoryLatest, summarizeConversation }) {
 const router = express.Router();
 router.post('/api/chat', requireAuth, async (req,res)=>{ const {message,conversation_id}=req.body||{}; const settings=await readSettings(); const id=conversation_id||randomUUID(); const cpath=path.join(CONVERSATIONS_DIR, `${id}.json`); const conv=await readJson(cpath,{id,messages:[],memory_summary_pending:false,memory_summary_count:0,last_summarized_at:null,last_summarized_message_count:0,last_summarized_user_count:0}); conv.messages.push({role:'user',content:message,created_at:new Date().toISOString()}); const ai=await callDeepSeek(settings,[{role:'system',content:CONSTITUTION},...conv.messages.map((x)=>({role:x.role,content:x.content}))]); conv.messages.push({role:'assistant',content:ai,created_at:new Date().toISOString()}); conv.updated_at=new Date().toISOString(); const totalMessages=conv.messages.length; const userTotal=conv.messages.filter((m)=>m.role==='user').length; const newMessagesSinceLastSummary=totalMessages-(conv.last_summarized_message_count||0); const userMessagesSinceLastSummary=userTotal-(conv.last_summarized_user_count||0); if (newMessagesSinceLastSummary>=8 && userMessagesSinceLastSummary>=3 && (conv.memory_summary_count||0)<3) conv.memory_summary_pending=true; await writeJson(cpath,conv); res.json({conversation_id:id,reply:ai,used_memories:[]}); });
 router.post('/api/chat/summarize', requireAuth, async (req,res)=>{ const {conversation_id}=req.body||{}; if(!conversation_id) return res.status(400).json({error:'缺少conversation_id'}); try { const result = await summarizeConversation(conversation_id, { ROOT: path.join(__dirname, '..'), readJson, writeJson, readSettings }); res.json({ status:'done', ...result }); } catch (e) { res.status(500).json({ error: e.message }); } });
 router.get('/api/chat/summarize', requireAuth, async (req,res)=>res.json({success:true}));
 return router;
};
