const express = require('express');
const { randomUUID } = require('crypto');
module.exports = function createMemoryRoutes(deps) {
  const { requireAuth, readMemory, MEMORY_PATH, readJson, TIMEZONE, writeMemoryLatest, writeJson, dateStr, estimateTokens, recalcTokens, readSettings, sendBark, callDeepSeek } = deps;
  const router = express.Router();
  router.get('/api/memory', requireAuth, async (req, res) => res.json(await readMemory(MEMORY_PATH, readJson, TIMEZONE)));
  router.post('/api/memory', requireAuth, async (req, res) => { const body = req.body || {}; const type = body.type || 'knowledge'; await writeMemoryLatest(MEMORY_PATH, readJson, writeJson, TIMEZONE, async (m) => { const item = { id: randomUUID(), title: body.title || '未命名', content: body.content || '', source: body.source || '手动', tags: body.tags || [], type, date_created: dateStr(TIMEZONE), date_updated: dateStr(TIMEZONE), importance: body.importance || 5, tokens: estimateTokens(body.content || ''), decay_score: type === 'identity' ? 10 : (body.decay_score ?? 10), related_ids: [], history: [], conflict: false }; m[type].push(item); recalcTokens(m); if (m.meta.total_tokens > m.meta.soft_limit) { const s = await readSettings(); await sendBark(s.bark_token, '记忆库已达软上限，建议进行AI修剪'); } return m; }); res.json({ success: true }); });
  router.put('/api/memory/:id', requireAuth, async (req, res) => { await writeMemoryLatest(MEMORY_PATH, readJson, writeJson, TIMEZONE, async (m) => { for (const t of ['identity', 'knowledge', 'inference', 'archive']) m[t] = m[t].map((i) => i.id === req.params.id ? { ...i, ...req.body, date_updated: dateStr(TIMEZONE) } : i); recalcTokens(m); return m; }); res.json({ success: true }); });
  router.delete('/api/memory/:id', requireAuth, async (req, res) => { await writeMemoryLatest(MEMORY_PATH, readJson, writeJson, TIMEZONE, async (m) => { for (const t of ['identity', 'knowledge', 'inference', 'archive']) m[t] = m[t].filter((x) => x.id !== req.params.id); recalcTokens(m); return m; }); res.json({ success: true }); });
  router.get('/api/memory/import-report', requireAuth, async (req, res) => res.json({ success: true }));
  router.post('/api/memory/prune', requireAuth, async (req, res) => { const settings = await readSettings(); const memory = await readMemory(MEMORY_PATH, readJson, TIMEZONE); const candidates = [...memory.identity, ...memory.knowledge, ...memory.inference]; const prompt = "你是记忆修剪助手。请分析记忆数组并给出建议。严格返回JSON：{\"suggestions\":[{\"id\":\"\",\"action\":\"archive|merge|lower_confidence\",\"reason\":\"\",\"merge_with\":\"\"}]}"; let raw = '{"suggestions":[]}'; try { raw = await callDeepSeek(settings, [{ role: 'system', content: prompt }, { role: 'user', content: JSON.stringify(candidates) }]); } catch (e) { console.log('记忆修剪建议生成失败：', e.message); } let parsed = { suggestions: [] }; try { parsed = JSON.parse(raw); } catch {} res.json({ status: 'done', suggestions: parsed.suggestions || [] }); });
  return router;
};
