const express = require('express');
const fs = require('fs').promises;
const path = require('path');
const { requireAuth } = require('../middleware/auth');
const { readUserData, getUserReportsPath, ensureDir } = require('../lib/userData');
const { runDailyJob } = require('../lib/reportGenerator');
const { fetchAllData } = require('../lib/dataFetcher');
const router = express.Router();
router.use(requireAuth);
router.get('/report', async(req,res)=>{ const dir=getUserReportsPath(req.user.userId); await ensureDir(dir); const files=(await fs.readdir(dir).catch(()=>[])).filter(f=>f.endsWith('.html')).sort(); if(!files.length) return res.send('暂无报告，将在今日09:00自动生成'); res.send(await fs.readFile(path.join(dir, files.at(-1)),'utf-8'));});
router.get('/trigger', async(req,res)=>{ runDailyJob(req.user.userId, { fetchAllData }).catch(e=>console.log('手动触发失败：',e.message)); res.json({success:true,message:'报告生成中'});});
router.get('/api/latest-data', async(req,res)=>{ const d=await readUserData(req.user.userId,'latest-data.json'); if(!d || Object.keys(d).length===0) return res.json({empty:true}); res.json(d);});
router.get('/weekly', async(req,res)=>{ const dir=path.join(getUserReportsPath(req.user.userId),'weekly'); await ensureDir(dir); const files=(await fs.readdir(dir).catch(()=>[])).filter(f=>f.endsWith('.html')).sort(); if(!files.length) return res.send('暂无周报'); res.send(await fs.readFile(path.join(dir, files.at(-1)),'utf-8'));});
module.exports=router;
