const express = require('express');
module.exports = function ({ fs, path, REPORTS_DIR, LATEST_DATA_PATH, readJson, getSafeSettings, runDailyJob, readSettings, fetchAllData, writeJson, CONVERSATIONS_DIR, dateStr, TIMEZONE, CONSTITUTION, readTasks, TASKS_PATH }) { const router=express.Router();
router.get('/api/latest-data', async (req,res)=>{ try{ const latest=await readJson(LATEST_DATA_PATH,{}); if(latest.settings) latest.settings=getSafeSettings(latest.settings); res.json(latest);}catch{res.json({empty:true});}});
router.get('/report', async (req,res)=>{ const files=(await fs.readdir(REPORTS_DIR).catch(()=>[])).filter((f)=>f.endsWith('.html')).sort(); if(!files.length) return res.send('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><body>暂无报告，将在今日09:00自动生成</body></html>'); let html=await fs.readFile(path.join(REPORTS_DIR,files.at(-1)),'utf-8');
const inject=`<script>(async()=>{const token=localStorage.getItem('morning_os_token')||'';const h={'Content-Type':'application/json','Authorization':token?'Bearer '+token:''};const d=await (await fetch('/api/research',{headers:h})).json().catch(()=>({topics:[]}));const active=(d.topics||[]).filter(x=>x.status==='active');function pickTopic(){if(!active.length){alert('暂无进行中的研究主题');return null;}const v=prompt('输入研究主题ID：\n'+active.map(t=>t.id+' '+t.title).join('\n'));return active.find(x=>x.id===v)||null;}document.querySelectorAll('a[href^="http"]').forEach(a=>{const b=document.createElement('button');b.textContent='收藏到研究';b.style.marginLeft='8px';b.onclick=async()=>{const t=pickTopic();if(!t)return;await fetch('/api/research/'+t.id+'/materials',{method:'POST',headers:h,body:JSON.stringify({title:a.textContent.trim(),url:a.href,summary:(a.parentElement?.innerText||'').slice(0,120),source_type:'morning_report',source_date:new Date().toISOString().slice(0,10)})});alert('已收藏');};a.insertAdjacentElement('afterend',b);});})();</script>`;
if(html.includes('</body>')) html=html.replace('</body>',inject+'</body>'); else html+=inject; res.send(html);});
router.get('/trigger', async (req,res)=>{ runDailyJob({ readSettings, fetchAllData, writeJson, latestDataPath: LATEST_DATA_PATH, conversationsDir: CONVERSATIONS_DIR, reportsDir: REPORTS_DIR, dateStr: () => dateStr(TIMEZONE), CONSTITUTION, readTasks: () => readTasks(TASKS_PATH, readJson) }).catch((e)=>console.log('手动触发失败：',e.message)); res.json({success:true,message:'报告生成中，请稍后访问 /report 查看'});});
router.get('/weekly', async (req,res)=>res.redirect('/report'));
return router; };
