const express = require('express');
const { randomUUID } = require('crypto');
const { requireAuth } = require('../middleware/auth');
const { readUserData, writeUserData, getUserSettings } = require('../lib/userData');
const { extractFromConversation } = require('../lib/extractor');
const { trackInteraction } = require('../lib/behaviorTracker');
const router = express.Router();
router.use(requireAuth);
const base = { tasks: [], inbox: [], watch: [], today_task_id: null };
const get = async (u) => ({ ...base, ...(await readUserData(u, 'tasks.json')) });
router.get('/', async (req,res)=>res.json(await get(req.user.userId)));
router.post('/', async (req,res)=>{ const d=await get(req.user.userId); const item={id:`task_${randomUUID().slice(0,8)}`,...req.body,status:req.body?.status||'todo',created_at:new Date().toISOString()}; d.tasks.push(item); await writeUserData(req.user.userId,'tasks.json',d); trackInteraction(req.user.userId,{ type:'task_added', meta:{ id:item.id, title:item.title }}).catch(()=>{}); res.json({success:true});});
router.put('/:id', async(req,res)=>{ const d=await get(req.user.userId); ['tasks','inbox','watch'].forEach(k=>d[k]=d[k].map(x=>x.id===req.params.id?{...x,...req.body,updated_at:new Date().toISOString()}:x)); await writeUserData(req.user.userId,'tasks.json',d); res.json({success:true});});
router.delete('/:id', async(req,res)=>{ const d=await get(req.user.userId); ['tasks','inbox','watch'].forEach(k=>d[k]=d[k].filter(x=>x.id!==req.params.id)); await writeUserData(req.user.userId,'tasks.json',d); res.json({success:true});});
router.post('/:id/move', async(req,res)=>{ const d=await get(req.user.userId); const all=[...d.tasks,...d.inbox,...d.watch]; const item=all.find(x=>x.id===req.params.id); if(!item) return res.status(404).json({error:'任务不存在'}); ['tasks','inbox','watch'].forEach(k=>d[k]=d[k].filter(x=>x.id!==req.params.id)); item.status=req.body?.status||'todo'; (item.status==='watch'?d.watch:d.tasks).push(item); await writeUserData(req.user.userId,'tasks.json',d); res.json({success:true});});
router.post('/today', async(req,res)=>{ const d=await get(req.user.userId); let id=req.body?.id; if(!id){const t={id:`task_${randomUUID().slice(0,8)}`,title:req.body?.title||'今日主任务',status:'todo'}; d.tasks.push(t); id=t.id;} d.today_task_id=id; await writeUserData(req.user.userId,'tasks.json',d); res.json({success:true});});
router.get('/today', async(req,res)=>{ const d=await get(req.user.userId); res.json({task:d.tasks.find(x=>x.id===d.today_task_id)||null});});
router.post('/confirm-inbox/:id', async(req,res)=>{ const d=await get(req.user.userId); const x=d.inbox.find(i=>i.id===req.params.id); if(!x) return res.status(404).json({error:'任务不存在'}); d.inbox=d.inbox.filter(i=>i.id!==x.id); d.tasks.push({...x,status:'todo'}); await writeUserData(req.user.userId,'tasks.json',d); res.json({success:true});});
router.post('/extract', async(req,res)=>{ const settings = await getUserSettings(req.user.userId); const result = await extractFromConversation(settings, req.body?.conversation || [], { source_type: 'conversation', userId: req.user.userId }); res.json(result);});
module.exports = router;
