const axios = require('axios');
const { randomUUID } = require('crypto');
const { TOOLS } = require('./agentTools');
const { getUserMemory, saveUserMemory, getUserTasks, saveUserTasks, getUserResearch } = require('./userData');
const { trackInteraction } = require('./behaviorTracker');
async function executeTool(toolName, args, userId, settings) { try { switch (toolName) {
case 'search_memory': { const memory = await getUserMemory(userId); const all=[...(memory.identity||[]),...(memory.knowledge||[]),...(memory.inference||[])]; const keywords=(args.query||'').split(/\s+/); const results=all.filter(m=>keywords.some(k=>(m.title||'').includes(k)||(m.content||'').includes(k))).slice(0,5); return {results:results.map(m=>({title:m.title,content:m.content,type:m.type}))}; }
case 'add_memory': { const memory=await getUserMemory(userId); const newMemory={id:`mem_${randomUUID().slice(0,8)}`,type:args.type||'knowledge',title:args.title,content:args.content,tags:args.tags||[],source_type:'ai_autonomous',confidence:0.75,stability:'medium',needs_review:true,importance:args.importance||6,decay_score:10,use_count:0,last_used_at:null,date_created:new Date().toISOString().split('T')[0],date_updated:new Date().toISOString().split('T')[0],history:[]}; const arr=memory[newMemory.type]||[]; arr.push(newMemory); memory[newMemory.type]=arr; memory.meta=memory.meta||{}; memory.meta.total_tokens=(memory.meta.total_tokens||0)+Math.floor((args.content||'').length/2); await saveUserMemory(userId,memory); return {success:true,id:newMemory.id,title:newMemory.title,message:'已存入记忆库，标记为待确认'}; }
case 'add_task': { const tasks=await getUserTasks(userId); const newTask={id:`task_${randomUUID().slice(0,8)}`,title:args.title,status:'todo',priority:args.priority||3,due_at:args.due_at||null,source_type:'ai_autonomous',confidence:0.8,needs_review:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}; tasks.tasks=tasks.tasks||[]; tasks.tasks.push(newTask); await saveUserTasks(userId,tasks); return {success:true,id:newTask.id,title:newTask.title,message:'已添加到任务列表，标记为待确认'}; }
case 'search_research': { const research=await getUserResearch(userId); const keywords=(args.query||'').split(/\s+/); const results=(research.topics||[]).filter(t=>keywords.some(k=>(t.title||'').includes(k)||(t.description||'').includes(k))).slice(0,3); return {results:results.map(t=>({id:t.id,title:t.title,conclusion:t.current_conclusion}))}; }
case 'get_latest_news': { const { fetchNews } = require('../sources/news'); const data=await fetchNews(settings); return data.success?{articles:(data.data||[]).slice(0,5)}:{error:'新闻获取失败'}; }
case 'get_market_data': { const { fetchExchange } = require('../sources/exchange'); const { fetchMetals } = require('../sources/metals'); const [ex,metals]=await Promise.allSettled([fetchExchange(settings),fetchMetals(settings)]); return {exchange:ex.status==='fulfilled'?ex.value.data:null,metals:metals.status==='fulfilled'?metals.value.data:null}; }
default: return {error:`未知工具：${toolName}`}; }} catch(e){ return {error:`工具执行失败：${e.message}`}; } }
async function runAgentLoop(messages, systemPrompt, userId, settings, maxRounds = 3) { let currentMessages=[...messages], usedTools=[], autoActions=[]; for(let round=0;round<maxRounds;round++){ const response=await axios.post('https://api.deepseek.com/v1/chat/completions',{model:'deepseek-chat',max_tokens:1500,messages:[{role:'system',content:systemPrompt},...currentMessages],tools:TOOLS,tool_choice:'auto'},{headers:{Authorization:`Bearer ${settings.deepseek_api_key}`,'Content-Type':'application/json'}}); const choice=response.data.choices[0]; if(choice.finish_reason==='tool_calls'){ const toolResults=[]; for(const call of (choice.message.tool_calls||[])){ const args=JSON.parse(call.function.arguments||'{}'); const result=await executeTool(call.function.name,args,userId,settings); usedTools.push({name:call.function.name,args,result}); trackInteraction(userId,{type:'tool_called',meta:{name:call.function.name}}).catch(()=>{}); if(['add_memory','add_task'].includes(call.function.name)) autoActions.push({tool:call.function.name,...result}); toolResults.push({role:'tool',tool_call_id:call.id,content:JSON.stringify(result)}); } currentMessages=[...currentMessages,choice.message,...toolResults]; } else return {reply:choice.message.content,usedTools,autoActions}; }
const lastResponse=await axios.post('https://api.deepseek.com/v1/chat/completions',{model:'deepseek-chat',max_tokens:1500,messages:[{role:'system',content:systemPrompt},...currentMessages]},{headers:{Authorization:`Bearer ${settings.deepseek_api_key}`,'Content-Type':'application/json'}}); return {reply:lastResponse.data.choices[0].message.content,usedTools,autoActions}; }
module.exports = { executeTool, runAgentLoop };
