const { query } = require('./db');

async function initDB() {
  await query(`CREATE TABLE IF NOT EXISTS users (id VARCHAR(50) PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL, password_hash TEXT NOT NULL, role VARCHAR(20) DEFAULT 'user', invite_quota INTEGER DEFAULT 3, invites_used INTEGER DEFAULT 0, invited_by VARCHAR(50), is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), last_login_at TIMESTAMPTZ)`);
  await query(`CREATE TABLE IF NOT EXISTS invites (id VARCHAR(50) PRIMARY KEY, code VARCHAR(20) UNIQUE NOT NULL, type VARCHAR(20) DEFAULT 'user', created_by VARCHAR(50), used_by VARCHAR(50), used_at TIMESTAMPTZ, is_used BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS user_settings (user_id VARCHAR(50) PRIMARY KEY, settings JSONB DEFAULT '{}', updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS memories (id VARCHAR(50) PRIMARY KEY, user_id VARCHAR(50) NOT NULL, type VARCHAR(20) NOT NULL, title TEXT, content TEXT, tags JSONB DEFAULT '[]', source_type VARCHAR(50), source_conversation_id VARCHAR(50), confidence FLOAT DEFAULT 0.7, stability VARCHAR(20) DEFAULT 'medium', needs_review BOOLEAN DEFAULT false, importance INTEGER DEFAULT 5, decay_score INTEGER DEFAULT 10, use_count INTEGER DEFAULT 0, last_used_at DATE, expires_at DATE, conflict BOOLEAN DEFAULT false, history JSONB DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS tasks (id VARCHAR(50) PRIMARY KEY, user_id VARCHAR(50) NOT NULL, title TEXT NOT NULL, description TEXT, status VARCHAR(20) DEFAULT 'todo', priority INTEGER DEFAULT 3, due_at TIMESTAMPTZ, source_type VARCHAR(50), source_conversation_id VARCHAR(50), related_memory_ids JSONB DEFAULT '[]', tags JSONB DEFAULT '[]', confidence FLOAT DEFAULT 1.0, needs_review BOOLEAN DEFAULT false, checklist JSONB DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS conversations (id VARCHAR(50) PRIMARY KEY, user_id VARCHAR(50) NOT NULL, messages JSONB DEFAULT '[]', memory_summary_pending BOOLEAN DEFAULT false, memory_summary_count INTEGER DEFAULT 0, last_summarized_at TIMESTAMPTZ, last_summarized_message_count INTEGER DEFAULT 0, last_summarized_user_count INTEGER DEFAULT 0, memory_summary JSONB, updated_at TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS research_topics (id VARCHAR(50) PRIMARY KEY, user_id VARCHAR(50) NOT NULL, title TEXT, description TEXT, status VARCHAR(20) DEFAULT 'active', tags JSONB DEFAULT '[]', linked_memory_ids JSONB DEFAULT '[]', linked_task_ids JSONB DEFAULT '[]', current_conclusion TEXT, pending_questions JSONB DEFAULT '[]', viewpoints JSONB DEFAULT '[]', materials JSONB DEFAULT '[]', journal JSONB DEFAULT '[]', auto_generated BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS reports (id VARCHAR(50) PRIMARY KEY, user_id VARCHAR(50) NOT NULL, date DATE NOT NULL, type VARCHAR(20) DEFAULT 'daily', content TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(user_id, date, type))`);
  await query(`CREATE TABLE IF NOT EXISTS portraits (user_id VARCHAR(50) PRIMARY KEY, data JSONB DEFAULT '{}', generated_at TIMESTAMPTZ DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS latest_data (user_id VARCHAR(50) PRIMARY KEY, data JSONB DEFAULT '{}', updated_at TIMESTAMPTZ DEFAULT NOW())`);
  console.log('数据库表初始化完成');
}

module.exports = { initDB };
