const fs = require('fs').promises;
const path = require('path');
const axios = require('axios');
const { getUserMemory, getUserTasks, getUserConversationPath, writeUserData } = require('./userData');
async function generatePortrait(userId, settings) { const memory=await getUserMemory(userId); const tasks=await getUserTasks(userId); const convDir=getUserConversationPath(userId); const tagFrequency={}; [...(memory.knowledge||[]),...(memory.inference||[])].forEach(m=>(m.tags||[]).forEach(tag=>{tagFrequency[tag]=(tagFrequency[tag]||0)+1;})); const topTags=Object.entries(tagFrequency).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([tag,count])=>({tag,count})); const convFiles=await fs.readdir(convDir).catch(()=>[]); const recentMessages=[]; for(const f of convFiles.slice(-20)){ try{ const conv=JSON.parse(await fs.readFile(path.join(convDir,f),'utf8')); recentMessages.push(...(conv.messages||[]).filter(m=>m.role==='user').slice(-3).map(m=>m.content)); }catch(e){} }
const analysisPrompt=`分析以下用户数据，生成认知画像。严格只返回JSON：\n{"top_interests":["最关注的3-5个领域"],"question_patterns":["用户常见的提问类型"],"thinking_style":"一句话描述用户思维特点","recent_focus_shift":"最近兴趣有无明显迁移","recurring_themes":["反复出现主题"],"knowledge_gaps":["可能的知识盲区"]}\n高频标签：${JSON.stringify(topTags)}\n最近提问样本：${recentMessages.slice(-10).join('\n')}\n注意：只做客观分析，不做性格判断、情绪分析、价值观评价。`;
const response=await axios.post('https://api.deepseek.com/v1/chat/completions',{model:'deepseek-chat',max_tokens:800,messages:[{role:'user',content:analysisPrompt}]},{headers:{Authorization:`Bearer ${settings.deepseek_api_key}`,'Content-Type':'application/json'}}); let portrait={}; try{portrait=JSON.parse((response.data.choices[0].message.content||'').replace(/```json|```/g,'').trim());}catch(e){}
const result={generated_at:new Date().toISOString(),top_tags:topTags,portrait,total_memories:(memory.identity||[]).length+(memory.knowledge||[]).length+(memory.inference||[]).length,total_tasks:(tasks.tasks||[]).length,total_conversations:convFiles.length}; await writeUserData(userId,'portrait.json',result); return result; }
module.exports = { generatePortrait };
