const path = require('path');
const DATA_ROOT = process.env.DATA_ROOT || path.join(process.cwd(), 'data');
const { query } = require('./db');

const DEFAULTS = {
  settings: { agent_enabled: true, portrait_auto_generate: true },
  memory: { identity: [], knowledge: [], inference: [], archive: [], meta: { total_tokens: 0, soft_limit: 40000, hard_limit: 50000 } },
  tasks: { tasks: [], inbox: [], watch: [], meta: {} },
  research: { topics: [] }
};

function getDefaultSettings() { return { ...DEFAULTS.settings }; }
function getUserDataPath(userId) { return path.join(DATA_ROOT, 'users', userId); }
function getUserConversationPath(userId) { return path.join(getUserDataPath(userId), 'conversations'); }
function getUserReportsPath(userId) { return path.join(getUserDataPath(userId), 'reports'); }
async function ensureDir() {}
async function ensureDataDirs() {}

async function getUserSettings(userId) { try { const r = await query('SELECT settings FROM user_settings WHERE user_id=$1', [userId]); return r.rows[0]?.settings || getDefaultSettings(); } catch (e) { console.error('读取用户设置失败', e.message); return getDefaultSettings(); } }
async function saveUserSettings(userId, settings) { try { await query('INSERT INTO user_settings (user_id, settings, updated_at) VALUES ($1,$2,NOW()) ON CONFLICT (user_id) DO UPDATE SET settings=$2, updated_at=NOW()', [userId, JSON.stringify(settings)]); } catch (e) { console.error('保存用户设置失败', e.message); } }

async function getUserMemory(userId) { try { const r = await query('SELECT * FROM memories WHERE user_id=$1 ORDER BY created_at ASC', [userId]); const rows = r.rows; return { meta: { total_tokens: rows.reduce((s, m) => s + Math.floor(((m.content) || '').length / 2), 0), soft_limit: 40000, hard_limit: 50000 }, identity: rows.filter(m => m.type === 'identity'), knowledge: rows.filter(m => m.type === 'knowledge'), inference: rows.filter(m => m.type === 'inference'), archive: rows.filter(m => m.type === 'archive') }; } catch (e) { console.error('读取记忆库失败', e.message); return { ...DEFAULTS.memory }; } }
async function saveMemoryItem(userId, item) { try { await query(`INSERT INTO memories (id,user_id,type,title,content,tags,source_type,source_conversation_id,confidence,stability,needs_review,importance,decay_score,use_count,last_used_at,expires_at,conflict,history,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,NOW(),NOW()) ON CONFLICT (id) DO UPDATE SET type=$3,title=$4,content=$5,tags=$6,confidence=$9,stability=$10,needs_review=$11,importance=$12,decay_score=$13,use_count=$14,last_used_at=$15,expires_at=$16,conflict=$17,history=$18,updated_at=NOW()`, [item.id, userId, item.type || 'knowledge', item.title || '', item.content || '', JSON.stringify(item.tags || []), item.source_type || null, item.source_conversation_id || null, item.confidence ?? 0.7, item.stability || 'medium', item.needs_review ?? false, item.importance ?? 5, item.decay_score ?? 10, item.use_count ?? 0, item.last_used_at || null, item.expires_at || null, item.conflict ?? false, JSON.stringify(item.history || [])]); } catch (e) { console.error('保存记忆项失败', e.message); } }
async function deleteMemoryItem(userId, memoryId) { try { await query('DELETE FROM memories WHERE id=$1 AND user_id=$2', [memoryId, userId]); } catch (e) { console.error('删除记忆项失败', e.message); } }
async function saveUserMemory(userId, data) { const items = ['identity', 'knowledge', 'inference', 'archive'].flatMap(k => (data[k] || []).map(i => ({ ...i, type: i.type || k }))); try { await query('DELETE FROM memories WHERE user_id=$1', [userId]); for (const item of items) await saveMemoryItem(userId, item); } catch (e) { console.error('保存记忆库失败', e.message); } }

async function getUserTasks(userId) { try { const r = await query('SELECT * FROM tasks WHERE user_id=$1 ORDER BY created_at ASC', [userId]); return { tasks: r.rows.filter(t => ['todo', 'doing', 'done', 'cancelled', 'snoozed'].includes(t.status)), inbox: r.rows.filter(t => t.status === 'inbox'), watch: r.rows.filter(t => t.status === 'watch') }; } catch (e) { console.error('读取任务失败', e.message); return { ...DEFAULTS.tasks }; } }
async function saveTaskItem(userId, item) { try { await query(`INSERT INTO tasks (id,user_id,title,description,status,priority,due_at,source_type,source_conversation_id,related_memory_ids,tags,confidence,needs_review,checklist,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,NOW(),NOW()) ON CONFLICT (id) DO UPDATE SET title=$3,description=$4,status=$5,priority=$6,due_at=$7,related_memory_ids=$10,tags=$11,confidence=$12,needs_review=$13,checklist=$14,updated_at=NOW()`, [item.id, userId, item.title || '', item.description || '', item.status || 'todo', item.priority || 3, item.due_at || null, item.source_type || null, item.source_conversation_id || null, JSON.stringify(item.related_memory_ids || []), JSON.stringify(item.tags || []), item.confidence || 1, item.needs_review || false, JSON.stringify(item.checklist || [])]); } catch (e) { console.error('保存任务失败', e.message); } }
async function deleteTaskItem(userId, taskId) { try { await query('DELETE FROM tasks WHERE id=$1 AND user_id=$2', [taskId, userId]); } catch (e) { console.error('删除任务失败', e.message); } }
async function saveUserTasks(userId, data) { try { await query('DELETE FROM tasks WHERE user_id=$1', [userId]); for (const item of [...(data.tasks || []), ...(data.inbox || []), ...(data.watch || [])]) await saveTaskItem(userId, item); } catch (e) { console.error('保存任务列表失败', e.message); } }

async function getUserResearch(userId) { try { const r = await query('SELECT * FROM research_topics WHERE user_id=$1 ORDER BY created_at ASC', [userId]); return { topics: r.rows }; } catch (e) { console.error('读取研究主题失败', e.message); return { ...DEFAULTS.research }; } }
async function saveResearchTopic(userId, topic) { try { await query(`INSERT INTO research_topics (id,user_id,title,description,status,tags,linked_memory_ids,linked_task_ids,current_conclusion,pending_questions,viewpoints,materials,journal,auto_generated,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,NOW(),NOW()) ON CONFLICT (id) DO UPDATE SET title=$3,description=$4,status=$5,tags=$6,linked_memory_ids=$7,linked_task_ids=$8,current_conclusion=$9,pending_questions=$10,viewpoints=$11,materials=$12,journal=$13,updated_at=NOW()`, [topic.id, userId, topic.title || '', topic.description || '', topic.status || 'active', JSON.stringify(topic.tags || []), JSON.stringify(topic.linked_memory_ids || []), JSON.stringify(topic.linked_task_ids || []), topic.current_conclusion || '', JSON.stringify(topic.pending_questions || []), JSON.stringify(topic.viewpoints || []), JSON.stringify(topic.materials || []), JSON.stringify(topic.journal || []), topic.auto_generated || false]); } catch (e) { console.error('保存研究主题失败', e.message); } }
async function deleteResearchTopic(userId, topicId) { try { await query('DELETE FROM research_topics WHERE id=$1 AND user_id=$2', [topicId, userId]); } catch (e) { console.error('删除研究主题失败', e.message); } }
async function saveUserResearch(userId, data) { try { await query('DELETE FROM research_topics WHERE user_id=$1', [userId]); for (const topic of (data.topics || [])) await saveResearchTopic(userId, topic); } catch (e) { console.error('保存研究数据失败', e.message); } }

async function readUserData(userId, filename) { if (filename === 'settings.json') return getUserSettings(userId); if (filename === 'memory.json') return getUserMemory(userId); if (filename === 'tasks.json') return getUserTasks(userId); if (filename === 'research.json') return getUserResearch(userId); if (filename === 'latest-data.json') { const r = await query('SELECT data FROM latest_data WHERE user_id=$1', [userId]); return r.rows[0]?.data || {}; } if (filename === 'portrait.json') { const r = await query('SELECT data FROM portraits WHERE user_id=$1', [userId]); return r.rows[0]?.data || {}; } return {}; }
async function writeUserData(userId, filename, data) { if (filename === 'settings.json') return saveUserSettings(userId, data); if (filename === 'memory.json') return saveUserMemory(userId, data); if (filename === 'tasks.json') return saveUserTasks(userId, data); if (filename === 'research.json') return saveUserResearch(userId, data); if (filename === 'latest-data.json') return query('INSERT INTO latest_data (user_id,data,updated_at) VALUES ($1,$2,NOW()) ON CONFLICT (user_id) DO UPDATE SET data=$2, updated_at=NOW()', [userId, JSON.stringify(data)]); if (filename === 'portrait.json') return query('INSERT INTO portraits (user_id,data,generated_at) VALUES ($1,$2,NOW()) ON CONFLICT (user_id) DO UPDATE SET data=$2, generated_at=NOW()', [userId, JSON.stringify(data)]); }

module.exports = { DATA_ROOT, getDefaultSettings, getUserDataPath, getUserConversationPath, getUserReportsPath, ensureDir, ensureDataDirs, readUserData, writeUserData, getUserSettings, saveUserSettings, getUserMemory, saveUserMemory, saveMemoryItem, deleteMemoryItem, getUserTasks, saveUserTasks, saveTaskItem, deleteTaskItem, getUserResearch, saveUserResearch, saveResearchTopic, deleteResearchTopic };
